import type { Product, Settings, OpeningHours, ProductCategory } from './types';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Порција 5 ќебапи',
    description:
      'Пет свежо изработени ќебапи од квалитетно месо, подготвени на скара. Сервирани со леб и црвен лук.',
    price: 150,
    category: 'Скара' as ProductCategory,
    image_url: '/images/1.jpeg',
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p2',
    name: 'Порција 10 ќебапи',
    description:
      'Десет сочни ќебапи, домешно подготвени по традиционална рецепта. Сервирани со домашен леб.',
    price: 250,
    category: 'Скара' as ProductCategory,
    image_url: '/images/1.jpeg',
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p3',
    name: 'Тавче гравче со 5 ќебапи',
    description:
      'Класично македонско тавче гравче во комбинација со пет сочни ќебапи. Комплетно и заситувачки.',
    price: 260,
    category: 'Скара' as ProductCategory,
    image_url: '/images/4.jpg',
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p4',
    name: 'Тавче гравче',
    description:
      'Автентично македонско тавче гравче подготвено по стара рецепта со свежо пасуљ, Piper и зачини.',
    price: 150,
    category: 'Скара' as ProductCategory,
    image_url: '/images/4.jpg',
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Сендвич со плескавица',
    description:
      'Домашна плескавица од прсно телешко месо, во свеж леб со салата, домат и сос.',
    price: 150,
    category: 'Скара' as ProductCategory,
    image_url: '/images/2.jpeg',
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p6',
    name: 'Сендвич со стек',
    description:
      'Голем и сочен стек во свеж леб, заедно со свежи зеленчукови и избрани сосови.',
    price: 170,
    category: 'Скара' as ProductCategory,
    image_url: '/images/3.jpg',
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p7',
    name: 'Пилешка чорба',
    description:
      'Топла и хранлива пилешка чорба со домашни зачини и јаболчно месо.',
    price: 150,
    category: 'Чорби' as ProductCategory,
    image_url: '/images/2.jpeg',
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p8',
    name: 'Coca-Cola',
    description: 'Освежувачка кола напитка, 0.5л',
    price: 80,
    category: 'Пијалоци' as ProductCategory,
    image_url: null,
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p9',
    name: 'Fanta',
    description: 'Освежувачка портокалова соковита напитка, 0.5л',
    price: 80,
    category: 'Пијалоци' as ProductCategory,
    image_url: null,
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p10',
    name: 'Schweppes',
    description: 'Швепс тоник, 0.5л',
    price: 80,
    category: 'Пијалоци' as ProductCategory,
    image_url: null,
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p11',
    name: 'Fanta Tropical',
    description: 'Тропски вкус Fanta, мешавина од тропски овошја, 0.5л',
    price: 80,
    category: 'Пијалоци' as ProductCategory,
    image_url: null,
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p12',
    name: 'Gazosa',
    description: 'Освежувачка лимонада со јагодов вкус, 0.5л',
    price: 80,
    category: 'Пијалоци' as ProductCategory,
    image_url: null,
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p13',
    name: 'Обична вода',
    description: 'Природна минерална вода без гас, 0.5л',
    price: 50,
    category: 'Пијалоци' as ProductCategory,
    image_url: null,
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p14',
    name: 'Кисела вода',
    description: 'Природна минерална вода со гас, 0.5л',
    price: 60,
    category: 'Пијалоци' as ProductCategory,
    image_url: null,
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const FALLBACK_SETTINGS: Settings = {
  id: 'main',
  restaurant_name: 'Ќебапчилница Вучко',
  phone: '078-495-591',
  email: 'ahmedidelil0@gmail.com',
  address: 'Ростуше, Северна Македонија',
  instagram_url: '',
  facebook_url: '',
  delivery_available: true,
  delivery_area: 'Ростуше и околина',
  online_ordering_open: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const FALLBACK_OPENING_HOURS: OpeningHours[] = [
  { id: '1', day_of_week: 1, day_name: 'Понеделник', open_time: '08:00', close_time: '22:00', closed: false, updated_at: '' },
  { id: '2', day_of_week: 2, day_name: 'Вторник', open_time: '08:00', close_time: '22:00', closed: false, updated_at: '' },
  { id: '3', day_of_week: 3, day_name: 'Среда', open_time: '08:00', close_time: '22:00', closed: false, updated_at: '' },
  { id: '4', day_of_week: 4, day_name: 'Четврток', open_time: '08:00', close_time: '22:00', closed: false, updated_at: '' },
  { id: '5', day_of_week: 5, day_name: 'Петок', open_time: '08:00', close_time: '22:00', closed: false, updated_at: '' },
  { id: '6', day_of_week: 6, day_name: 'Сабота', open_time: '08:00', close_time: '22:00', closed: false, updated_at: '' },
  { id: '7', day_of_week: 7, day_name: 'Недела', open_time: null, close_time: null, closed: true, updated_at: '' },
];
